server:
  port: 8084 # Port du service Gateway

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Permet la découverte automatique des services avec Eureka
          lower-case-service-id: true # Nom de service en minuscule
      routes:
        - id: patient_service_route_get_all
          uri: lb://patient-service # Load balancer pour accéder au service patient
          predicates:
            - Path=/api/patients/all
          filters:
            - name: Retry
              args:
                retries: 3 # Nombre de tentatives
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT # Codes déclencheurs
                methods: GET # Méthode concernée

        - id: patient_service_route_get_by_id
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/getPatient/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
                methods: GET

        - id: patient_service_route_create
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/create
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
                methods: POST

        - id: patient_service_route_update
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/update/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
                methods: PUT

        - id: patient_service_route_delete
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/delete/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
                methods: DELETE

        - id: patient_service_route_check_exists
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
                methods: GET

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # Timeout pour Hystrix en ms

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.example.gateway: DEBUG
