server:
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    ip-address: 172.21.2.181
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5




spring:
  application:
    name: praticien-service

management:
  security:
    enabled: false

logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG